version: '3.1'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - /efs/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=myrootpassword
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myusername
      - MYSQL_PASSWORD=mypassword
    restart: always
  wordpress:
    image: wordpress:php7.3-fpm-alpine
    volumes:
      - /efs/db:/var/www/html
    depends_on:
      - mysql
    environment:
      - WORDPRESS_DB_HOST=mysql
      - MYSQL_ROOT_PASSWORD=myrootpassword
      - WORDPRESS_DB_NAME=mydatabase
      - WORDPRESS_DB_USER=mydbuser
      - WORDPRESS_DB_PASSWORD=mypassword
      - WORDPRESS_TABLE_PREFIX=wp_
    links:
      - mysql
    restart: always
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8181:80'
    environment:
      - PMA_HOST=mysql
      - MYSQL_ROOT_PASSWORD=myrootpassword
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /efs/db:/var/www/html
    ports:
      - 8080:80
    links:
      - wordpress